/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        imagenUser = new javax.swing.JLabel();
        etiquetaUser = new javax.swing.JLabel();
        etiquetaPass = new javax.swing.JLabel();
        cajaUser = new javax.swing.JTextField();
        cajaPass = new javax.swing.JPasswordField();
        btnInicio = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setBackground(new java.awt.Color(51, 153, 255));
        botonSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panel.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 70, 30));

        imagenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        panel.add(imagenUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, 200));

        etiquetaUser.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiquetaUser.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaUser.setText("Usuario: ");
        panel.add(etiquetaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        etiquetaPass.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiquetaPass.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaPass.setText("Contrasenia: ");
        panel.add(etiquetaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        cajaUser.setBackground(new java.awt.Color(255, 255, 255));
        cajaUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cajaUser.setForeground(new java.awt.Color(0, 0, 0));
        panel.add(cajaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 210, 30));

        cajaPass.setBackground(new java.awt.Color(255, 255, 255));
        cajaPass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cajaPass.setForeground(new java.awt.Color(0, 0, 0));
        panel.add(cajaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 180, 30));

        btnInicio.setBackground(new java.awt.Color(0, 102, 102));
        btnInicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(204, 0, 204));
        btnInicio.setText("Iniciar Sesion");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 140, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        panel.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0); // cierra el programa
    }//GEN-LAST:event_botonSalirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        
        String userCorrecto = "Fezk3", passwordCorrecto = "uwu";
        
        if(userCorrecto.equals(cajaUser.getText())){
            
            String pass = "";
            for(int i=0;i<cajaPass.getPassword().length;i++){
             
                pass += cajaPass.getPassword()[i];
                
            }
            
            if(passwordCorrecto.equals(pass)){
             
                JOptionPane.showMessageDialog(null, "Ingresaste al sistema");
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Error Contrasenia desconocida");
                
            }
            
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Error Usuario desconocido");
            
        }
        
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton btnInicio;
    private javax.swing.JPasswordField cajaPass;
    private javax.swing.JTextField cajaUser;
    private javax.swing.JLabel etiquetaPass;
    private javax.swing.JLabel etiquetaUser;
    private javax.swing.JLabel imagenUser;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
