/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class Ventana extends javax.swing.JFrame {
    
    private Timer tiempo;
    private int centesima = 0, segundos = 0, minutos = 0, horas = 0;
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            centesima++;
            if(centesima == 100){
                segundos++;
                centesima = 0;
            }
            if(segundos == 60){  
                minutos ++;
                segundos = 0;
            }
            if(minutos == 60){
                horas ++;
                minutos = 0; 
            }
            
            actualizarEtiTiempo();
            
        }
    };
    
    private void actualizarEtiTiempo(){
        
        String texto = (horas<=9?"0":"") + horas + ":" +(minutos<=9?"0":"") + minutos + ":" +(segundos<=9?"0":"") + segundos +":" + (centesima<=9?"0":"") + centesima;
        etiquetaTiempo.setText(texto);
        
    }

    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // inicializando obj tiempo
        tiempo = new Timer(10, acciones);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        imagenCronometro = new javax.swing.JLabel();
        etiquetaCronometro = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JButton();
        BotonPausa = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenCronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cronometro.png"))); // NOI18N
        panel.add(imagenCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 150));

        etiquetaCronometro.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiquetaCronometro.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCronometro.setText("Cronometro");
        panel.add(etiquetaCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        etiquetaTiempo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("00:00:00:00");
        panel.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 120, 50));

        BotonInicio.setBackground(new java.awt.Color(255, 153, 51));
        BotonInicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonInicio.setText("Iniciar");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });
        panel.add(BotonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, -1));

        BotonPausa.setBackground(new java.awt.Color(255, 153, 51));
        BotonPausa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonPausa.setText("Pausar");
        BotonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausaActionPerformed(evt);
            }
        });
        panel.add(BotonPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 100, -1));

        botonDetener.setBackground(new java.awt.Color(255, 153, 51));
        botonDetener.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonDetener.setText("Detener");
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        panel.add(botonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 110, -1));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image.png"))); // NOI18N
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        
        tiempo.start();
        BotonInicio.setEnabled(false);
        BotonInicio.setText("Reanudar");
        BotonPausa.setEnabled(true);
        botonDetener.setEnabled(true);
        
    }//GEN-LAST:event_BotonInicioActionPerformed

    private void BotonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausaActionPerformed
        
        tiempo.stop();
        BotonPausa.setEnabled(false);
        BotonInicio.setEnabled(true);
        
    }//GEN-LAST:event_BotonPausaActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        
        if(tiempo.isRunning()){
            
            tiempo.stop();
            BotonInicio.setEnabled(true);
            
        }
       
        BotonInicio.setText("Iniciar");
        BotonPausa.setEnabled(false);
        botonDetener.setEnabled(false);
        
        horas = 0;
        minutos = 0;
        segundos = 0;
        centesima = 0;
        
        actualizarEtiTiempo();
        
    }//GEN-LAST:event_botonDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton BotonPausa;
    private javax.swing.JButton botonDetener;
    private javax.swing.JLabel etiquetaCronometro;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel imagenCronometro;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
